global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'github-linkedin-analyzer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  - job_name: 'workers'
    static_configs:
      - targets: ['worker:9090']

rules:
  groups:
    - name: github_linkedin_analyzer_alerts
      rules:
        - alert: HighErrorRate
          expr: rate(errors_total[5m]) > 0.1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High error rate detected"
            description: "Error rate is above 10% for the last 5 minutes"

        - alert: APIRateLimitNearingLimit
          expr: rate_limit_remaining{service="github"} < 100
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "GitHub API rate limit running low"
            description: "Less than 100 API calls remaining"

        - alert: HighResponseTime
          expr: rate(request_duration_seconds_sum[5m]) / rate(request_duration_seconds_count[5m]) > 2
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High response time detected"
            description: "Average response time is above 2 seconds for the last 5 minutes"

        - alert: HighMemoryUsage
          expr: container_memory_usage_bytes{container_name=~"app|worker"} > 900000000
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage detected"
            description: "Container using more than 900MB of memory"

        - alert: QueueBacklog
          expr: active_requests > 50
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Request queue building up"
            description: "More than 50 requests in the queue"

recording_rules:
  groups:
    - name: github_linkedin_analyzer_metrics
      interval: 1m
      rules:
        - record: job:request_duration_seconds:avg_rate5m
          expr: rate(request_duration_seconds_sum[5m]) / rate(request_duration_seconds_count[5m])
        
        - record: job:request_errors:rate5m
          expr: rate(errors_total[5m])
        
        - record: job:active_requests:max5m
          expr: max_over_time(active_requests[5m])
